# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-06 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paster', '0002_paste_shortcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='shortcode',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
